import pino from 'pino';
import { env } from './env.js';

const secretFields = [
  'password',
  'currentPassword',
  'newPassword',
  'passwordHash',
  'token',
  'tokenHash',
  'otp',
  'otpHash',
  'accessToken',
  'refreshToken',
  '*.password',
  '*.currentPassword',
  '*.newPassword',
  '*.passwordHash',
  '*.token',
  '*.tokenHash',
  '*.otp',
  '*.otpHash',
  '*.accessToken',
  '*.refreshToken',
  'req.body.password',
  'req.body.currentPassword',
  'req.body.newPassword',
  'req.body.passwordHash',
  'req.body.token',
  'req.body.tokenHash',
  'req.body.otp',
  'req.body.otpHash',
  'req.body.accessToken',
  'req.body.refreshToken',
  'req.query.token',
  'req.params.token',
  'req.cookies',
  'req.headers.authorization',
  'req.headers.cookie',
  'req.headers["x-csrf-token"]',
  'req.raw.headers.authorization',
  'req.raw.headers.cookie',
  'req.raw.headers["x-csrf-token"]',
  'res.headers["set-cookie"]',
];

export const logger = pino({
  level: env.LOG_LEVEL,
  redact: { paths: secretFields, censor: '[REDACTED]' },
});
